name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 3.101.104.186 # TODO replace to your EC2 instance public IP
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # TODO define this secret in your GitHub repo settings

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 600 mykey.pem
          
          # Create the directory on the EC2 instance if it doesn't exist
ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP "mkdir -p ~/NetflixMovieCatalog"

# Copy the files from the current work dir into the EC2 instance, under `~/NetflixMovieCatalog/`
scp -o StrictHostKeyChecking=no -i mykey.pem -r * ubuntu@$EC2_PUBLIC_IP:~/NetflixMovieCatalog/

# Execute the `deploy.sh` script on the EC2 instance
ssh -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash ~/NetflixMovieCatalog/deploy.sh"
          
